inventory_master/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
]

main/urls.py
from django.urls import path
from main.views import create_product_flutter, show_main, create_item, show_xml, show_json, show_xml_by_id, \
    show_json_by_id, register, login_user, logout_user, increase_amount, decrease_amount, show_json_user, \
    delete_item_ajax, edit_item, get_item_json, create_ajax

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-item', create_item, name='create_item'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'), 
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('increase-amount/<int:id>/', increase_amount, name='increase_amount'),
    path('decrease-amount/<int:id>/', decrease_amount, name='decrease_amount'),
    path('delete-item-ajax/<int:id>/', delete_item_ajax, name='delete_item_ajax'),
    path('edit-item/<int:id>', edit_item, name='edit_item'),
    path('get-item-json/', get_item_json, name='get_item_json'),
    path('create-ajax/', create_ajax, name='create_ajax'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

class Item(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    amount = models.IntegerField()
    description = models.TextField()
    date_added = models.DateField(auto_now_add=True, null=True)
    category = models.CharField(max_length=255)

main/forms.py
from django.forms import ModelForm
from main.models import Item

class ItemForm(ModelForm):
    class Meta:
        model = Item
        fields = ["name", "amount", "description", "category"]

main/views.py
import datetime
import json
from django.http import HttpResponseRedirect, HttpResponse, HttpResponseNotFound, JsonResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import logout
from django.contrib.auth import authenticate, login
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages  
from django.core import serializers
from main.forms import ItemForm
from main.models import Item

@login_required(login_url='/login')
def show_main(request):
    items = Item.objects.filter(user=request.user)
    total_items = len(items)

    context = {
        'app_name': request.user.username + "'s Inventory Master",
        'name': request.user.username,
        'class': 'PBP A',
        'items': items,
        'total_items': total_items,
        'last_login': request.COOKIES.get('last_login'),
    }

    return render(request, "main.html", context)

def increase_amount(request, id):   # Wrong conditionals before, ini harusnya langsung GET
    item = get_object_or_404(Item, pk=id, user=request.user)
    item.amount += 1
    item.save()
    return HttpResponseRedirect(reverse('main:show_main'))

def decrease_amount(request, id):   # Wrong conditionals before, ini harusnya langsung GET
    item = get_object_or_404(Item, pk=id, user=request.user)
    if item.amount > 1:
        item.amount -= 1
        item.save()
    else:
        item.delete()
    return HttpResponseRedirect(reverse('main:show_main'))

def create_item(request):
    form = ItemForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        item = form.save(commit=False)
        item.user = request.user
        item.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "create_item.html", context)

def edit_item(request, id):
    # Get item berdasarkan ID
    item = Item.objects.get(pk = id)

    # Set item sebagai instance dari form
    form = ItemForm(request.POST or None, instance=item)

    if form.is_valid() and request.method == "POST":
        # Simpan form dan kembali ke halaman awal
        form.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "edit_item.html", context)

def show_xml(request):
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main")) 
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Sorry, incorrect username or password. Please try again.')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

def get_item_json(request):
    item_data = Item.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize('json', item_data))

@csrf_exempt
def create_ajax(request):
    if request.method == 'POST':
        name = request.POST.get("name")
        amount = request.POST.get("amount")
        description = request.POST.get("description")
        category = request.POST.get("category")
        user = request.user

        new_item = Item(name=name, amount=amount, description=description, user=user, category=category)
        new_item.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

@csrf_exempt
def delete_item_ajax(request, id):
    if request.method == 'DELETE':
        item = get_object_or_404(Item, pk=id, user=request.user)
        item.delete()
        return HttpResponse(b"DELETED", status=201)

    return HttpResponseNotFound()

@csrf_exempt
def create_product_flutter(request):
    if request.method == 'POST':
        
        data = json.loads(request.body)

        new_product = Item.objects.create(
            user = request.user,
            name = data["name"],
            amount = int(data["amount"]),
            description = data["description"],
            date_added = data["date_added"],
            category = data["category"],
        )

        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)
    
def show_json_user(request):
    data = Item.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

main/templates/create_item.html
{% extends 'base.html' %} 

{% block content %}
<h1>Add New Item</h1>

<form method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Add Item"/>
            </td>
        </tr>
    </table>
</form>

{% endblock %}

main/templates/edit_item.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h1 class="card-title">Edit Item</h1>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        <table class="table">
                            {{ form.as_table }}
                        </table>
                        <div class="text-center mt-3">
                            <button type="submit" class="btn btn-primary">Edit Item</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<style>
    /* Latar belakang */
    html, body {
        background: linear-gradient(to bottom right, white, #8f94fb);
        background-attachment: scroll;
        min-height: 100vh;
        margin: 0;
    }

    /* Tombol Edit Item */
    .btn-primary {
        background-color: #007bff;
        border-color: #007bff;
    }
</style>
{% endblock %}

main/templates/login.html
{% extends 'base.html' %}

{% block meta %}
    <title>Login</title>
{% endblock meta %}

{% block content %}

<div class="login">
    {% if messages %}
    <div class="alert">
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    </div>
    {% endif %}

    <section class="vh-100 gradient-custom">
        <div class="container py-5 h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-12 col-md-8 col-lg-6 col-xl-5">
                    <div class="card bg-dark text-white" style="border-radius: 1rem;">
                        <div class="card-body p-5 text-center">

                            <div class="mb-md-5 mt-md-4 pb-5">

                                <h2 class="fw-bold mb-2 text-uppercase">Login</h2>
                                <p class="text-white-50 mb-5">Please enter your username and password!</p>

                                <form method="POST" action="">
                                    {% csrf_token %}
                                    <div class="form-outline form-white mb-4">
                                        <div class="input-group">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text">
                                                    <i class="fas fa-user"></i> <!-- Username icon -->
                                                </span>
                                            </div>
                                            <input type="text" name="username" placeholder="Username" class="form-control" />
                                        </div>
                                    </div>
                                
                                    <div class="form-outline form-white mb-4">
                                        <div class="input-group">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text">
                                                    <i class="fas fa-lock"></i> <!-- Password icon -->
                                                </span>
                                            </div>
                                            <input type="password" name="password" placeholder="Password" class="form-control" />
                                        </div>
                                    </div>
                                
                                    <button class="btn btn-outline-light btn-lg px-5 login_btn" type="submit" value="login">Login</button>
                                </form>                                

                            </div>

                            <div>
                                <p class="mb-0">Don't have an account? <a href="{% url 'main:register' %}">Register Now</a></p>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

</div>

<style>
    html, body {
        background: linear-gradient(to bottom right, #4e54c8, #8f94fb); /* Replace with your desired background color */
        background-attachment: scroll; /* This prevents the background from scrolling */
        min-height: 100vh;
        margin: 0;
    }

    /* Adjust button color */
    .login_btn {
        background-color: #4e54c8;
        color: white;
    }

    /* Optional: Style form labels */
    .form-label {
        color: white;
    }

    .form-control {
        font-size: 18px; /* Adjust the desired font size */
        border-radius: 10px 0 0 10px; /* Increase this value for more rounded corners */
    }

    /* Increase the size of icons */
   .input-group-text i {
       font-size: 30px; /* Adjust the desired icon size */
   }

    /* Optional: Add some padding to the form */
    .form-outline {
        padding: 1rem;
    }

    .alert {
        color: white;
        background-color: black;
    }
</style>

{% endblock content %}

main/templates/main.html
{% extends 'base.html' %}

{% block content %}
    <nav class="navbar bg-dark border-bottom border-body" data-bs-theme="dark">
        <div class="container-fluid">
        <a class="navbar-brand">{{ app_name }}</a>
        <form class="d-flex" role="logout">
            <span class="navbar-text ml-3" style="margin-right: 15px;"> Welcome {{ name }} from {{ class }} </span>
            <a href="{% url 'main:logout' %}">
                <button class="btn btn-outline-success" type="button">Logout</button>
            </a>
        </form>
        </div>
    </nav>

    <center>
    <div class="container mt-4">
        <h2>An inventory to manage inventories</h2>
        <hr>

        <p>Terdapat <span id="total-items"> {{ total_items }} </span> inventory yang telah dimasukkan</p>

        <div class="card main">
            <div class="card-body d-flex flex-wrap" id="item-list-container">
                <!-- Moved content in the JavaScript with AJAX -->
            </div>
        </div>        

        
        <!-- Modals for AJAX -->
        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h1 class="modal-title fs-5" id="exampleModalLabel">Add New Item</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <form id="form" onsubmit="return false;">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="name" class="col-form-label">Name:</label>
                                <input type="text" class="form-control" id="name" name="name"></input>
                            </div>
                            <div class="mb-3">
                                <label for="amount" class="col-form-label">Amount:</label>
                                <input type="number" class="form-control" id="amount" name="amount"></input>
                            </div>
                            <div class="mb-3">
                                <label for="description" class="col-form-label">Description:</label>
                                <textarea class="form-control" id="description" name="description"></textarea>
                            </div>
                            <div class="mb-3">
                                <label for="category" class="col-form-label">Category:</label>
                                <input type="text" class="form-control" id="category" name="category"></input>
                            </div>
                        </form>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <button type="button" class="btn btn-primary" id="button_add" data-bs-dismiss="modal">Add Item</button>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="mt-3">
            <a href="{% url 'main:create_item' %}">
                <button class="btn btn-danger button-33" role="button">Add New Item</button>
            </a>
        </div>
        <button type="button" class="btn btn-primary button-33" role="button" data-bs-toggle="modal" data-bs-target="#exampleModal">Add Item by AJAX</button>
        
        <h5>Sesi terakhir login: {{ last_login }}</h5>
    </div>
    </center>

    <style>
    html, body {
        background: linear-gradient(to bottom right, white, #8f94fb); /* Ganti dengan warna latar belakang atau properti CSS lainnya yang diinginkan */
        background-attachment: scroll; /* Ini mencegah latar belakang menggulir */
        min-height: 100vh;
        margin: 0;
    }

    .main {
        max-width: 100%; /* Menggunakan lebar maksimum untuk tampilan desktop */
    }

    /* Mengatur tampilan samping-sampingan menggunakan Flexbox */
    .item-card {
        background: linear-gradient(to bottom right, white, #8f94fb); /* Ganti dengan warna latar belakang atau properti CSS lainnya yang diinginkan */
        flex: 0 0 calc(50% - 20px); /* 50% lebar, dengan margin sebesar 10px */
        margin: 10px;
    }

    .last-item-card {
        background: linear-gradient(to bottom right, #4e54c8, #8f94fb); /* Ganti dengan warna latar belakang atau properti CSS lainnya yang diinginkan */
        color: white; /* Ganti dengan warna teks yang sesuai */
    }

    /* CSS Button from internet*/
    .button-33 {
        background-color: #c2fbd7;
        border-radius: 100px;
        box-shadow: rgba(44, 187, 99, .2) 0 -25px 18px -14px inset,rgba(44, 187, 99, .15) 0 1px 2px,rgba(44, 187, 99, .15) 0 2px 4px,rgba(44, 187, 99, .15) 0 4px 8px,rgba(44, 187, 99, .15) 0 8px 16px,rgba(44, 187, 99, .15) 0 16px 32px;
        color: rgb(0, 0, 0);
        cursor: pointer;
        display: inline-block;
        font-family: CerebriSans-Regular,-apple-system,system-ui,Roboto,sans-serif;
        padding: 7px 20px;
        text-align: center;
        text-decoration: none;
        transition: all 250ms;
        border: 0;
        font-size: 16px;
        user-select: none;
        -webkit-user-select: none;
        touch-action: manipulation;
        margin-top: 1%;
        margin-bottom: 1%;
    }

    .button-33:hover {
        box-shadow: rgba(44,187,99,.35) 0 -25px 18px -14px inset,rgba(44,187,99,.25) 0 1px 2px,rgba(44,187,99,.25) 0 2px 4px,rgba(44,187,99,.25) 0 4px 8px,rgba(44,187,99,.25) 0 8px 16px,rgba(44,187,99,.25) 0 16px 32px;
        transform: scale(1.05) rotate(-1deg);
    }

    </style>

<script>
    async function getItems() {
        return fetch("{% url 'main:get_item_json' %}").then((res) => res.json());
    }

    async function refreshItem() {
        const itemListContainer = document.getElementById("item-list-container");
        const items = await getItems();
        itemListContainer.innerHTML = "";

        items.forEach((item, index) => {
            // Create item card baru
            const itemCard = document.createElement("div");
            itemCard.className = "card mb-3 item-card";

            if (index === items.length - 1) {
                itemCard.classList.add("last-item-card");
            }

            // Populate konten item card
            itemCard.innerHTML = `
                <div class="card-header">${item.fields.name}</div>
                <div class="card-body">
                    <p><b>Amount:</b> ${item.fields.amount}</p>
                    <p><b>Date Added:</b> ${item.fields.date_added}</p>
                    <p><b>Category:</b> ${item.fields.category}</p>
                    <div class="btn-group" role="group">
                        <a> <button class="btn btn-success btn-sm mx-1" onclick="addAmount(${item.pk}); return false;"> + </button> </a>
                        <a> <button class="btn btn-success btn-sm mx-1" onclick="decAmount(${item.pk}); return false;"> - </button> </a>
                        <a> <button class="btn btn-danger btn-sm mx-1" onclick="deleteItem(${item.pk}); return false;"> Delete </button> </a>
                        <a href="edit-item/${item.pk}"> <button class="btn btn-primary btn-sm mx-1"> Edit </button> </a>
                        <!-- Button to trigger the description modal -->
                        <button class="btn btn-info btn-sm mx-1" data-bs-toggle="modal" data-bs-target="#descriptionModal${item.pk}">
                            Show Description
                        </button>
                    </div>
                </div>
            `;

            // Append item card ke container
            itemListContainer.appendChild(itemCard);

            // Create modal
            const modal = document.createElement("div");
            modal.className = "modal fade";
            modal.id = `descriptionModal${item.pk}`;
            modal.tabIndex = -1;
            modal.setAttribute("aria-labelledby", `descriptionModalLabel${item.pk}`);
            modal.setAttribute("aria-hidden", "true");

            modal.innerHTML = `
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="descriptionModalLabel${item.pk}">Description</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            ${item.fields.description}
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div>
            `;

            // Append modal ke container
            itemListContainer.appendChild(modal);
            
        });
        const itemsLength = items.length;
        document.getElementById("total-items").textContent = itemsLength;
    }

    refreshItem(); // Call functionnya

    function addItem() {
        fetch("{% url 'main:create_ajax' %}", {
            method: "POST",
            body: new FormData(document.querySelector('#form'))
        }).then(refreshItem)

        document.getElementById("form").reset()
        return false
    }

    document.getElementById("button_add").onclick = addItem

    function deleteItem(itemId) {
        fetch(`delete-item-ajax/${itemId}`, {
            method: "DELETE",
            
        }).then(refreshItem)
        return false
    }

    function addAmount(itemId) {
        fetch(`increase-amount/${itemId}`, {
            method: "GET",
            
        }).then(refreshItem)
        return false
    }

    function decAmount(itemId) {
        fetch(`decrease-amount/${itemId}`, {
            method: "GET",
            
        }).then(refreshItem)
        return false
    }
        
</script>

{% endblock content %}

main/templates/register.html
{% extends 'base.html' %}

{% block meta %}
    <title>Register</title>
{% endblock meta %}

{% block content %}

<div class="login">
    <section>
        <div class="container py-5 h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-12 col-md-8 col-lg-6 col-xl-5">
                    <div class="card bg-dark text-white" style="border-radius: 1rem;">
                        <div class="card-body p-5 text-center">

                            <div class="mb-md-5 mt-md-4 pb-5">

                                <h2 class="fw-bold mb-2 text-uppercase">Register an Account</h2>

                                <form method="POST">
                                    {% csrf_token %}
                                    <div class="form-outline form-white mb-4">
                                        <div class="input-group">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text">
                                                    <i class="fas fa-user"></i>
                                                </span>
                                            </div>
                                            <input type="text" name="username" class="form-control" placeholder="Username" />
                                        </div>
                                    </div>

                                    <div class="form-outline form-white mb-4">
                                        <div class="input-group">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text">
                                                    <i class="fas fa-lock"></i>
                                                </span>
                                            </div>
                                            <input type="password" name="password1" class="form-control" placeholder="Password" />
                                            <small id="passwordHelpBlock" class="form-text" style="color: rgb(150, 150, 150);">
                                                Your password must be 8-20 characters long, contain letters and numbers, and must not contain spaces, special characters, or emoji.
                                            </small>
                                        </div>
                                    </div>

                                    <div class="form-outline form-white mb-4">
                                        <div class="input-group">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text">
                                                    <i class="fas fa-lock"></i>
                                                </span>
                                            </div>
                                            <input type="password" name="password2" class="form-control" placeholder="Re-enter Password" />
                                        </div>
                                    </div>

                                    <button class="btn btn-outline-light btn-lg px-5" type="submit" name="submit" value="Daftar">Register</button>
                                </form>

                            </div>
                            <div>
                                <p class="mb-0">Already have an account? <a href="{% url 'main:login' %}">Login</a></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    {% if messages %}
    <div class="alert" role="alert">
        <div class="alert-text">
            <strong>Success:</strong>
            <ul>
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        </div>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endif %}

</div>

<style>
    html, body {
        background: linear-gradient(to bottom right, #4e54c8, #8f94fb);
        background-attachment: scroll;
        min-height: 100vh;
        margin: 0;
    }

    .btn-outline-light {
        background-color: #4e54c8;
        color: white;
    }

    .form-label {
        color: white;
    }

    .form-control {
        font-size: 18px;
        border-radius: 10px;
    }

    .input-group-text i {
        font-size: 30px;
    }

    .form-outline {
        padding: 1rem;
    }
</style>

{% endblock content %}